### ISSUE TITLE
version 1.9.14 with OpenSSL <1.1.0 breaks Crypt::OpenSSL::Verify

### ISSUE THREAD

**Issue by dakkar** [dsully/perl-crypt-openssl-x509#112]
## Description

building `Crypt::OpenSSL::Verify` with `Crypt::OpenSSL::X509` 1.9.14 and  OpenSSL 1.0.2g fails

cc @timlegge as maintainer of `::Verify`

### Expected behaviour

`Crypt::OpenSSL::Verify` should work pass its tests against latest `Crypt::OpenSSL::X509` as it does with older versions.

### Actual behaviour

`Crypt::OpenSSL::Verify` fails with "certificate signature failure" which, after some digging, turns out to be `error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm`

## Cause

Commit e0a60a0c5bd621ae9103db8cd3ef4727f63979bd effectively removed a call to `OPENSSL_add_all_algorithms_conf()`, in two ways:

1. it removed the parentheses (which was almost certainly a mistake)
2. it added a `#ifdef OPENSSL_LOAD_CONF` (and I don't know what this is for)

reverting those two changes fixes the problem.

## Operating system and version

This is a Ubuntu 16 (`Linux myhost 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`) with 

## Crypt::OpenSSL::X509 version

1.9.14

## Perl version

perl 5.30.0

## OpenSSL version

OpenSSL 1.0.2g  1 Mar 2016

**Comment by timlegge** [comment]
Thanks @dakkar I will keep an eye of this to see if I need to address

**Comment by jonasbn** [comment]
Hi @dakkar and @timlegge 

I have created a PR (#113) for the changes proposed above, it builds and passes tests on my machine, but it also did with the previous release.

If any of you have time could you give it a quick review, if I do not hear from you I will release tomorrow or Sunday, when I get some keyboard time

**Comment by jonasbn** [comment]
And @dakkar thanks for the elaborate issue

**Comment by dakkar** [comment]
Thank you! I'll test on Monday at work and I'll let you know (I'm pretty sure it will work, though)
