### ISSUE TITLE
2.0.0 tarball on the CPAN includes local files

### ISSUE THREAD

**Issue by gregoa** [dsully/perl-crypt-openssl-x509#120]
The 2.0.0 tarball as released on the CPAN contains `cpanfile.snapshot` but more importantly a `local/lib/` directory; this looks like a glitch in the release process …

https://metacpan.org/release/JONASBN/Crypt-OpenSSL-X509-2.0.0/source

Cheers,
gregor, Debian Perl Group

**Comment by gregoa** [comment]
Thanks for this change and the new CPAN release.

**Comment by jonasbn** [comment]
sorry about the delay, did not take the laptop with me on summer vacation
