### ISSUE TITLE
Badly parsed subjectAltName

### ISSUE THREAD

**Issue by dverdin** [dsully/perl-crypt-openssl-x509#40]
The email method is great but it has a flaw:

When a subjectAltName is set in the certificate with several alternate email addresses like, e.g.:
address1@domain.tld
address2@domain2.tld

email returns : address1@domain.tldaddress2@domain2.tld

It should return an array of emails if several addresses are found in this field.
Problem: this change is not backward compatible.
What about implementing a new sub, called for example "emails()" that would return such an array?
email() would keep on returning, say the first email found or instead, undef if there is no main email?
Another solution would be to always return an array with "email()".

I made a workaround in my own code, replacing this:

my %result_hash;
$result_hash{lc($x509->email)} = 1 if $x509->email;

by this:
    my $extensions = $x509->extensions_by_name();
    my %emails;
    foreach my $extension_name (keys %$extensions) {
        if ($extension_name eq 'subjectAltName') {
            my $extension_value = $extensions->{$extension_name}->value();
            my @addresses = split '..', $extension_value;
            shift @addresses;
            foreach my $address (@addresses) {
                $emails{$address} = 1;
            }
        }
    }
        my %result_hash;
    if (%emails) {
        foreach my $email (keys %emails) {
            $result_hash{lc($email)} =1;
        }
    }elsif($x509->email) {
        $result_hash{lc($x509->email)} = 1;
    }

Thank you for your time on this very valuable module!

Regards,

David

**Comment by cbiedl** [comment]
@dverdin, careful with that split operation, it rather works by accident. See #50 for the underlying problem.
