### ISSUE TITLE
META.yml version tag is incorrect

### ISSUE THREAD

**Issue by sorin-manole** [dsully/perl-crypt-openssl-x509#44]
https://github.com/dsully/perl-crypt-openssl-x509/blob/c1fadbcf332c25d54d3c4f6f2adbdd0936238e8a/META.yml

```
version: 1.804
```

should be 1.806

**Comment by jonasbn** [comment]
This error seems to be present in release 1.807 as well. Ref: https://metacpan.org/source/DANIEL/Crypt-OpenSSL-X509-1.807/META.yml

**Comment by jonasbn** [comment]
@dsully this issue has been addressed and it can be closed :-)
