### ISSUE TITLE
-Werror creates problems

### ISSUE THREAD

**Issue by chorny** [dsully/perl-crypt-openssl-x509#45]
Strawberry perl 5.18 has

```
/* #define USE_PERL_SBRK    /**/
```

in win32.h, which with "-Werror" dies with

```
error: "/*" within comment [-Werror=comment]
```

See for ex. http://www.cpantesters.org/cpan/report/6b653933-6c13-1014-a8f7-67a372e8df79

**Comment by jonasbn** [comment]
So the suggestion is to _tweak_ the compiler flags for Windows to avoid this issue?

**Comment by jonasbn** [comment]
My proposed solution is to add:

`-Wnoerror= comment` in `Makefile.PL`

But I cannot test it currently and make sure it works, since I cannot reproduce it.
