### ISSUE TITLE
Makefile.PL incorrectly reports libcrypto not available

### ISSUE THREAD

**Issue by skington** [dsully/perl-crypt-openssl-x509#47]
On a Debian 7.9 box, using Perl 5.20.3 installed via perlbrew, I get

> - libcrypto is not installed or not in the default lib path. Aborting.

dpkg --list and locate suggest that it's installed:

> root@ci:Crypt-OpenSSL-VerifyX509-0.10# locate libcrypto
> /usr/lib/libcrypto.so.0.9.8
> /usr/lib/x86_64-linux-gnu/libcrypto.a
> /usr/lib/x86_64-linux-gnu/libcrypto.so
> /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0

But those paths aren't in the list of paths searched:

>   DB<2> x $Config{libpth}  
> 0  '/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/4.4.5/include-fixed /usr/lib /lib/../lib /usr/lib/../lib /lib /lib64 /usr/lib64'

If I remove the check for libcrypto in Makefile.PL, make and make tests run happily.

**Comment by Chuckatron** [comment]
I just encountered this and finally discovered I was missing the `libssl-dev` package

**Comment by jonasbn** [comment]
This does not look like it was an issue with the Perl distribution.
