### ISSUE TITLE
Installing on Mac with HomeBrew

### ISSUE THREAD

**Issue by genio** [dsully/perl-crypt-openssl-x509#57]
Crypt::OpenSSL::X509 refuses to install on Macs where OpenSSL is installed via homebrew.

```
brew install openssl
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
cpanm IO::Socket::SSL
```

Is generally the path taken in this circumstance, however, with Crypt::OpenSSL::X509, one must:

```
cpanm --look Crypt::OpenSSL::X509
vim Makefile.PL
 + inc '-I/usr/local/opt/openssl/include -I/usr/include/openssl -I/usr/local/include/ssl -I/usr/local/ssl/include';
 + libs '-L/usr/local/opt/openssl/lib -L/usr/lib -L/usr/local/lib -L/usr/local/ssl/lib -lcrypto';
perl Makefile.PL
make
make test
make install
```

Could you please alter the Makefile.PL to use the above ENV variables if they're set?

**Comment by jonasbn** [comment]
Hello,

This might have been addressed in the latest release 1.8.8, which contains a patch I made, could you please verify?

Have a nice weekend,

jonasbn

**Comment by eserte** [comment]
On MacOSX Mojave with openssl from homebrew I have to use the following CPAN.pm distroprefs file for successful installation:
https://github.com/eserte/srezic-cpan-distroprefs/blob/e0d0843a0e28eb9d75ea762c32773e76a884161e/Crypt-OpenSSL-....yml#L8-L10
The highlighted sections is the args which have to be provided to "perl Makefile.PL".

**Comment by jonasbn** [comment]
I am closing this issue, since I regard it as fixed and original poster has not responded.

**Comment by nur-psoehnlein** [comment]
Anyone coming here in 2025? For me it worked with a command and path like this:
`OPENSSL_PREFIX="/opt/homebrew/opt/openssl@1.1/" cpanm Crypt::OpenSSL::X509`

**Comment by jonasbn** [comment]
@nur-psoehnlein have you tried with OpenSSL 3?
