### ISSUE TITLE
can't load X509.so 

### ISSUE THREAD

**Issue by dhairyareddy** [dsully/perl-crypt-openssl-x509#59]
Hi, 

I am insatlling Crypt::OpenSSL::X509 module and running test program is giving following error..

Really appreciate the help!

Can't load '/usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi/auto/Crypt/OpenSSL/X509/X509.so' for module Crypt::OpenSSL::X509: /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi/auto/Crypt/OpenSSL/X509/X509.so: undefined symbol: NETSCAPE_X509_it at /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/DynaLoader.pm line 230.
 at /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi/Crypt/OpenSSL/X509.pm line 91
Compilation failed in require at ./test.pl line 3.
BEGIN failed--compilation aborted at ./test.pl line 3.
Can't locate object method "__X509_cleanup" via package "Crypt::OpenSSL::X509" at /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi/Crypt/OpenSSL/X509.pm line 95.
END failed--call queue aborted at ./test.pl line 3.

cat test.pl
#!/usr/bin/perl
use strict;
use Crypt::OpenSSL::X509

**Comment by dhairyareddy** [comment]
make test failed too

$cd Crypt-OpenSSL-X509-1.807
$ make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/00-version.t t/pod.t t/utf8.t t/x509-ec.t t/x509.t
t/00-version.t .. 1/1 # Running Crypt::OpenSSL::X509 test suite against OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
t/00-version.t .. ok
t/pod.t ......... skipped: Test::Pod 1.00 required for testing POD
t/utf8.t ........ 1/11
#   Failed test 'use Crypt::OpenSSL::X509;'
#   at t/utf8.t line 12.
#     Tried to use 'Crypt::OpenSSL::X509'.
#     Error:  Can't load '/home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.so' for module Crypt::OpenSSL::X509: /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.so: undefined symbol: NETSCAPE_X509_it at /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/DynaLoader.pm line 230.
#  at /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/lib/Crypt/OpenSSL/X509.pm line 91
# Compilation failed in require at t/utf8.t line 12.
# BEGIN failed--compilation aborted at t/utf8.t line 12.
Can't locate object method "new_from_file" via package "Crypt::OpenSSL::X509" at t/utf8.t line 18.
Can't locate object method "__X509_cleanup" via package "Crypt::OpenSSL::X509" at /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/lib/Crypt/OpenSSL/X509.pm line 95.
END failed--call queue aborted.
# Looks like your test exited with 255 just after 1.
t/utf8.t ........ Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 11/11 subtests
t/x509-ec.t ..... 1/7
#   Failed test 'use Crypt::OpenSSL::X509;'
#   at t/x509-ec.t line 4.
#     Tried to use 'Crypt::OpenSSL::X509'.
#     Error:  Can't load '/home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.so' for module Crypt::OpenSSL::X509: /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.so: undefined symbol: NETSCAPE_X509_it at /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/DynaLoader.pm line 230.
#  at /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/lib/Crypt/OpenSSL/X509.pm line 91
# Compilation failed in require at t/x509-ec.t line 4.
# BEGIN failed--compilation aborted at t/x509-ec.t line 4.
Can't locate object method "new_from_file" via package "Crypt::OpenSSL::X509" at t/x509-ec.t line 6.
Can't locate object method "__X509_cleanup" via package "Crypt::OpenSSL::X509" at /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/lib/Crypt/OpenSSL/X509.pm line 95.
END failed--call queue aborted.
# Looks like your test exited with 255 just after 1.
t/x509-ec.t ..... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 7/7 subtests
t/x509.t ........ 1/54
#   Failed test 'use Crypt::OpenSSL::X509;'
#   at t/x509.t line 4.
#     Tried to use 'Crypt::OpenSSL::X509'.
#     Error:  Can't load '/home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.so' for module Crypt::OpenSSL::X509: /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.so: undefined symbol: NETSCAPE_X509_it at /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/DynaLoader.pm line 230.
#  at /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/lib/Crypt/OpenSSL/X509.pm line 91
# Compilation failed in require at t/x509.t line 4.
# BEGIN failed--compilation aborted at t/x509.t line 4.
Can't locate object method "new_from_file" via package "Crypt::OpenSSL::X509" at t/x509.t line 6.
Can't locate object method "__X509_cleanup" via package "Crypt::OpenSSL::X509" at /home/sdkashir/Crypt-OpenSSL-X509-1.807/blib/lib/Crypt/OpenSSL/X509.pm line 95.
END failed--call queue aborted.
# Looks like your test exited with 255 just after 1.
t/x509.t ........ Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 54/54 subtests

Test Summary Report
-------------------
t/utf8.t      (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 11 tests but ran 1.
t/x509-ec.t   (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 7 tests but ran 1.
t/x509.t      (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 54 tests but ran 1.
Files=5, Tests=4,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.21 cusr  0.03 csys =  0.28 CPU)
Result: FAIL
Failed 3/5 test programs. 3/4 subtests failed.
make: *** [test_dynamic] Error 255

**Comment by tla** [comment]
Hi - I'm having the same issue, Mac OS X Sierra 10.12.6, perl 5.26.0, openssl 1.0.2l installed via Homebrew. The `make` works fine but the tests all fail as above:

```#     Error:  Can't load '/Users/tla/.cpanm/work/1503691958.13777/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.bundle' for module Crypt::OpenSSL::X509: dlopen(/Users/tla/.cpanm/work/1503691958.13777/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.bundle, 2): Symbol not found: _NETSCAPE_X509_it
#   Referenced from: /Users/tla/.cpanm/work/1503691958.13777/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.bundle
#   Expected in: flat namespace
#  in /Users/tla/.cpanm/work/1503691958.13777/Crypt-OpenSSL-X509-1.807/blib/arch/auto/Crypt/OpenSSL/X509/X509.bundle at /usr/local/Cellar/perl/5.26.0/lib/perl5/5.26.0/darwin-thread-multi-2level/DynaLoader.pm line 197.
#  at /Users/tla/.cpanm/work/1503691958.13777/Crypt-OpenSSL-X509-1.807/blib/lib/Crypt/OpenSSL/X509.pm line 91.
# Compilation failed in require at t/x509.t line 4.
# BEGIN failed--compilation aborted at t/x509.t line 4.
Can't locate object method "new_from_file" via package "Crypt::OpenSSL::X509" at t/x509.t line 6.
Can't locate object method "__X509_cleanup" via package "Crypt::OpenSSL::X509" at /Users/tla/.cpanm/work/1503691958.13777/Crypt-OpenSSL-X509-1.807/blib/lib/Crypt/OpenSSL/X509.pm line 95.
END failed--call queue aborted.
# Looks like your test exited with 22 just after 1.```

**Comment by jonasbn** [comment]
Hi @tla 

Your issue might have been addressed in the latest release 1.8.8, which contains a patch I made, could you please verify?

Have a nice weekend,

jonasbn

**Comment by tla** [comment]
Yes that seems to have taken care of it (though I've upgraded to High Sierra in the meantime.) Many thanks!

**Comment by jonasbn** [comment]
Closing this issue based on above comment
