### ISSUE TITLE
BIO double free in CRL_Issuer

### ISSUE THREAD

**Issue by manison** [dsully/perl-crypt-openssl-x509#73]
This line

https://github.com/dsully/perl-crypt-openssl-x509/blob/91fbfceb5e3c31ca179be933cc1b653ed0a01900/X509.xs#L1588

causes the BIO to be freed twice which may result in segmentation fault.

**Comment by jonasbn** [comment]
Is this due to the same thing happening in line [1600](https://github.com/dsully/perl-crypt-openssl-x509/blob/91fbfceb5e3c31ca179be933cc1b653ed0a01900/X509.xs#L1600) ?

**Comment by manison** [comment]
> Is this due to the same thing happening in line [1600](https://github.com/dsully/perl-crypt-openssl-x509/blob/91fbfceb5e3c31ca179be933cc1b653ed0a01900/X509.xs#L1600) ?

Yes, first free is at line 1588 and second at line 1600.

**Comment by jonasbn** [comment]
Addressed in release 1.9.2 (1.902)

**Comment by jonasbn** [comment]
Thanks @manison
