### ISSUE TITLE
Question about the version format

### ISSUE THREAD

**Issue by perlpunk** [dsully/perl-crypt-openssl-x509#77]
This is not an issue with the module itself.
I am maintaining the perl module repository [devel:languages:perl](https://build.opensuse.org/project/show/devel:languages:perl) in SUSE's Open Build Service, and for historical reasons we take the module version as it is (and can't easily change that).
But for rpm, 1.9 will be lower than 1.813.
I know it is not required, but it would help us a lot if authors would always use the same amount of digits, e.g. 1.900.
https://github.com/perlpunk/perl5-module-meta

**Comment by jonasbn** [comment]
Hi @perlpunk 

My bad - I will have a look at it tonight

**Comment by perlpunk** [comment]
Just wanted to note - it's not a bug. For perl, the versions are correct, because 1.9 is semantically equal to 1.900.0.
Just that several linux vendors historically just took the versions as they are, and in their versioning system the order is different.

**Comment by perlpunk** [comment]
Thanks!
