### ISSUE TITLE
rt.cpan.org deprecation

### ISSUE THREAD

**Issue by jonasbn** [dsully/perl-crypt-openssl-x509#80]
Add bug report section

**Comment by skaji** [comment]
Now we set the github issue as bugtracker.
https://metacpan.org/release/JONASBN/Crypt-OpenSSL-X509-1.913-TRIAL/source/META.json#L43

**Comment by jonasbn** [comment]
Information on what bug tracker to use is implemented in 1.913 and will be further documented in 1.914

**Comment by jonasbn** [comment]
Hi @skaji 

This has been included in the release [1.9.14-TRIAL](https://github.com/dsully/perl-crypt-openssl-x509/releases/tag/1.9.14-TRIAL), just uploaded to PAUSE/CPAN.

Please let me know if you experience any issues or have any feedback. The 1.9.14 release will be made in due time depending on the outcome/feedback of the trial release.

Thanks for your contributions.
