### ISSUE TITLE
wrong output of emails

### ISSUE THREAD

**Issue by phanousk** [dsully/perl-crypt-openssl-x509#83]
If a certificate contains more e-mails in Alternative name, ie:
``` 
X509v3 Subject Alternative Name: 
    email:phanousek@cesnet.cz, email:petr.hanousek@cesnet.cz 
```

the output from `$x509->email()` function is very badly parsable as there is no delimiter between the mail addresses:
`petr.hanousek@cesnet.czphanousek@cesnet.cz`.

I suggest to change the return value of that function to an array. Maybe in case of only one mail address could remain scalar.

Openssl: OpenSSL 1.1.1d  10 Sep 2019
System: Debian 10.9, Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
Perl: v5.28.1

**Comment by jonasbn** [comment]
This surely looks like a bug, thank you

**Comment by phanousk** [comment]
> This surely looks like a bug, thank you

Unfortunatelly not new. Sorry for raising new issue when there is already https://github.com/dsully/perl-crypt-openssl-x509/issues/40 .
Petr

**Comment by jonasbn** [comment]
Hi @phanousk 

I will close this issue, but I will see if I can find the time to address #40 

Thanks for reporting the bug anyway - good to know it is still relevant #40 is somewhat old
