### ISSUE TITLE
Version number in META.yml is incorrect

### ISSUE THREAD

**Issue by timlegge** [dsully/perl-crypt-openssl-x509#86]
# Issue Template
Version number in META.yml is incorrect
## Description

Version number in META.yml is incorrect

### Expected behaviour

Correct verion in META.yml

### Actual behaviour

Some indexing issues were mentioned on irc

## Operating system and version

N/A

**Comment by jonasbn** [comment]
Yes I noticed, Module::Install is not particularly helpful.

![issue86](https://user-images.githubusercontent.com/75423/116822261-29c5f400-ab7e-11eb-95d2-b7ec81264a20.png)

**Comment by jonasbn** [comment]
I have just uploaded release version 1.907 this should address the issue.

The Module::Install documentation describes the use of an `.author/` directory in `inc/`, this does not seem to work, so I had to remove the `inc/`directory manually - I will keep an eye on the `META.yml` file.

Thinking about moving to [Dist::Zilla](https://metacpan.org/release/Dist-Zilla), since [Module::Install](https://metacpan.org/release/Module-Install) and do not really get along very well.

**Comment by timlegge** [comment]
Hi

I did some work on Dist:Zilla for Crypt-OpenSSL-Verify here is the dist.ini
that I used.  I thought I had a version that looked for the libraries but I
can't find it at the moment...

Tim

name    = Crypt-OpenSSL-Verify
abstract = OpenSSL Verify Perl Module
author  = Original Author: Timothy Legge ***@***.***>
copyright_holder = Timothy Legge, see the git log
; [...]
license = Perl_5
[Meta::Maintainers]
maintainer = Timothy Legge ***@***.***>
maintainer = Wesley Schwengle ***@***.***>

[Meta::Contributors]

[PruneCruft]
[ManifestSkip]
[MetaYAML]
[License]
[Readme]
[ExtraTests]
[ExecDir]
[ShareDir]
[MakeMaker]
'VERSION_FROM'  => 'Test.pm'
'XSMULTI'         => 1
'NEEDS_LINKING'   => 1
'CCFLAGS'         => "-Wall -Werror -DOPENSSL_API_COMPAT=0x10100000L"
'OPTIMIZE'        => '-O3'
XS      => '{ "lib/Crypt/OpenSSL/Verify.xs"    =>
"lib/Crypt/OpenSSL/Verify.c"}'

[Manifest]
[TestRelease]
[ConfirmRelease]
[UploadToCPAN]

[GatherDir]
exclude_filename = cpanfile
exclude_filename = Makefile.PL
exclude_filename = dev-bin/cpanm
exclude_match = xt\/testapp\/.*
exclude_filename = Dockerfile

[Encoding]
encoding = bytes
match = ico

[CPANFile]

[CopyFilesFromBuild::Filtered]
copy = cpanfile
copy = Makefile.PL

[CopyFilesFromRelease]
copy = cpanfile, Makefile.PL

[AutoPrereqs]
skip = Saml2Test

[Prereqs]
Crypt::OpenSSL::Bignum = 0

[CheckLib]
lib = crypto
header = openssl/crypto.h

[MetaJSON]
[MetaProvides::Package]

[Repository]
[PodSyntaxTests]
[PodCoverageTests]
[Test::Perl::Critic]
[Test::EOL]
[Test::EOF]
[Test::NoTabs]
[Test::TrailingSpace ]

[PodWeaver]
[VersionFromModule]
[AuthorsFromGit]
