### ISSUE TITLE
Install fails for Perl 5.20

### ISSUE THREAD

**Issue by racke** [dsully/perl-crypt-openssl-x509#95]
## Description

This module causes an abort for my Sympa Gitlab job: https://salsa.debian.org/sympa-team/sympa/-/jobs/2352397
All other Perl versions tested work fine.

Failure:

```
Building and testing Crypt-OpenSSL-X509-1.910 ... cp X509.pm blib/lib/Crypt/OpenSSL/X509.pm
Running Mkbootstrap for Crypt::OpenSSL::X509 ()
chmod 644 X509.bs
/root/.plenv/versions/5.20.3/bin/perl5.20.3 "-Iinc" /root/.plenv/versions/5.20.3/lib/perl5/site_perl/5.20.3/ExtUtils/xsubpp  -typemap /root/.plenv/versions/5.20.3/lib/perl5/5.20.3/ExtUtils/typemap -typemap typemap  X509.xs > X509.xsc && mv X509.xsc X509.c
Warning: Aliases 'subject_hash' and 'hash' have identical values in X509.xs, line 422
cc -c  -I/usr/local/opt/openssl/include -I/usr/local/include/openssl -I/usr/include/openssl -I/usr/local/include/ssl -I/usr/local/ssl/include -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -Wall -Werror   -DVERSION=\"1.910\" -DXS_VERSION=\"1.910\" -fPIC "-I/root/.plenv/versions/5.20.3/lib/perl5/5.20.3/x86_64-linux-thread-multi/CORE"   X509.c
In file included from /root/.plenv/versions/5.20.3/lib/perl5/5.20.3/x86_64-linux-thread-multi/CORE/perl.h:5199,
                 from X509.xs:2:
/root/.plenv/versions/5.20.3/lib/perl5/5.20.3/x86_64-linux-thread-multi/CORE/inline.h:196:1: error: 'S_croak_memory_wrap' defined but not used [-Werror=unused-function]
 S_croak_memory_wrap(void)
 ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:344: X509.o] Error 1
! Installing Crypt::OpenSSL::X509 failed. See /root/.cpanm/work/1641722497.40/build.log for details. Retry with --force to force install it.
```
Expiring 3 work directories.
FAIL
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1

### Expected behaviour

Installs without failure.

### Actual behaviour

Install fails, see above.

## Operating system and version

Docker container hatsoftwares/sympa-perl-5.20:latest

## Crypt::OpenSSL::X509 version

1.910

**Comment by jonasbn** [comment]
Up to now I have not been able to reproduce the issue, I can see the same issue in reports from CPAN testers, but noluck reproducing at this time.

My proposed solution is to add:

`-Wnoerror=unused-function` in `Makefile.PL`

But I cannot test it currently and make sure it works, since I cannot reproduce it.

I am wondering if this is due to the perls built for **plenv** and with _multi-threading_. I myself am using **Perlbrew** and not _multi-threaded_ perls.

**Comment by timlegge** [comment]
See
https://github.com/timlegge/perl-Crypt-OpenSSL-Verify/commit/e43029a8c7eda377ef45b66179d77cec839d1a14

**Comment by jonasbn** [comment]
@timlegge that is a good approach, I will see if I can accomodate
