### ISSUE TITLE
Idea: using Crypt::OpenSSL::Guess

### ISSUE THREAD

**Issue by skaji** [dsully/perl-crypt-openssl-x509#97]
## Description

Detecting openssl libraries is difficult.

There is a module that concentrates on that task, [Crypt::OpenSSL::Guess](https://metacpan.org/pod/Crypt::OpenSSL::Guess).
So how about using Crypt::OpenSSL::Guess in perl-crypt-openssl-x509's Makefile.PL?

### Expected behaviour

use Crypt::OpenSSL::Guess

### Actual behaviour

not using Crypt::OpenSSL::Guess

## Operating system and version

macOS 12.1

## Crypt::OpenSSL::X509 version

1.912

## Perl version

5.34.0

## OpenSSL version

1.1.1m / 3.0.1

**Comment by jonasbn** [comment]
Hi @skaji 

This sound very very interesting, but I need some time to evaluate the proposed enhancement.

**Comment by skaji** [comment]
@jonasbn Thank you for your reply.
I'm going to create a PR so that you can evaluate the use of Crypt::OpenSSL::Guess.

**Comment by jonasbn** [comment]
#104 implements this

**Comment by jonasbn** [comment]
Hi @ikedas and @michal-josef-spacek 

This has been included in the release [1.9.14-TRIAL](https://github.com/dsully/perl-crypt-openssl-x509/releases/tag/1.9.14-TRIAL), just uploaded to PAUSE/CPAN.

Please let me know if you experience any issues or have any feedback. The 1.9.14 release will be made in due time depending on the outcome/feedback of the trial release.

Thanks for your contributions.
